name: Docker Image CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_ACCESS_TOKEN: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
          docker-compose --version

      - name: Log in to Docker Hub
        run: echo $DOCKERHUB_ACCESS_TOKEN | docker login -u $DOCKERHUB_USERNAME --password-stdin

      - name: Get commit hash
        id: vars
        run: echo "::set-output name=commit_hash::$(echo $GITHUB_SHA | cut -c 1-7)"

      - name: Build Docker images
        run: docker-compose build

      - name: Tag Docker images
        run: |
          docker tag ga-service-01:latest $DOCKERHUB_USERNAME/ga-service-01:${{ steps.vars.outputs.commit_hash }}
          docker tag ga-service-02:latest $DOCKERHUB_USERNAME/ga-service-02:${{ steps.vars.outputs.commit_hash }}

      - name: Push Docker images
        run: |
          docker push $DOCKERHUB_USERNAME/ga-service-01:${{ steps.vars.outputs.commit_hash }}
          docker push $DOCKERHUB_USERNAME/ga-service-02:${{ steps.vars.outputs.commit_hash }}
